# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167vc2lEjzHkHiSbSPVNBDDmMQowVzIBT
"""

#program 1(i)
print("I am signing up for Replit&#39;s 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day.\nI'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.\nNo excuses for not coding from the middle of a field!")

#program 1(ii)
m={
    'spyware':'Spyware is a type of malicious software',
   'adware': 'term used for various pop-up advertisements that show up on your computer or mobile device',

}
print(m)
print(m.keys())
print(m['spyware'])

#program 2
i=float(12300)
v=(i*18)/100
net=v+i
print("-------------------------BILL------------------\n\n")
print("Cost of the mobile\t\t\t:\t",i)
print("GST of 18%\t\t\t\t:\t ",v)
print("\t\t\t\t\t\t---------")
print("Net price mobile\t\t\t:\t",net)
print("\t\t\t\t\t\t---------")

#program 4
i=(int(input("NUMBER OF STUDENTS:")))
if(i<10):
  name=input("NAME:")
  dob=(input("DATE OF BIRTH:"))
  doy=int(input("DATE OF YEAR:"))
  age=2022-doy
  print("AGE:",age)
  w=int(input("WEIGHT"))
  h=int(input("HEIGHT"))
  bmi=(w/h/h)*10000
  print("BMI:",bmi)
if(bmi<15):
  print("under weight")
elif(bmi<50):
  print("normal")
elif(bmi<100):
  print("----------------over weight--------------")

#program 5:
print("\t\t\tcalculating EB bill")
type=int(input("\n select the residntial palce:\n\n1.household\n2.commercial\n"))
if(type ==1):
  def house():
    print("EB Bill for your House:")
    
    unit=int(input("enter the units"))
    if(unit<=100):
        ui=unit*0.50
    elif unit>=101 and unit<201:
         ui=unit*0.75
    elif unit<201 and unit<301:
         ui=unit*1.20
    else:
         ui=unit*1.50
    print("total charges:",ui)
  house()  
if(type ==2):
     def com():
      print("NO PRICE IN THE QUESTION PAPER")    
     com()

import pandas as pd
df=pd.DataFrame({
     'offence': ['sending threaten message by email','sending defamatory msg by email','email spoofing'],
'law' : ['sec.503 IPC','Sec.499 IPC','sec.463'],
})
df