# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsQB_FZCaOZkLK5eOebjcQrvjiOKCov1
"""



import pandas as pd
df=pd.DataFrame({
 'NAME': ['stu1','stu2','stu3','stu4','stu5'],
'FATHER NAME' : ['f1','f2','f3','f4','f5'],
'doy' : [2001,2000,1978,2000,2000],
'STATUS':['son','daughter','son','daughter','son']
})
df['age']=2022-df['doy']
df['FATHER AGE']=2*df['age']
df['father status']=df['FATHER AGE'].apply (lambda x:'EXPIRED' if x>58 else 'IN SERVICE')
df['GENDER']=df['STATUS'].apply (lambda x:'male' if x=='son' else 'female') 
csv_data = df.to_csv()
print('\nCSV String:\n', csv_data)
df
ax1 = df.plot.scatter('age','FATHER AGE')
df.plot(kind='hist')
bx=df.boxplot('age','FATHER AGE')
plt.show()